### ISSUE TITLE
Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

### ISSUE THREAD

**Issue by salemba** [flofly/spring-batch-elasticsearch#3]
Hello. Thanks for the great post. I cloned your code, added getters and setters to CAR and Offer objects, created the mysql database, updated username and password, and ran the project.
I'm getting the following error : Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set.

Could you please check the full error trace [here](http://pastebin.com/bNWVWXmb)?

Et merci encore une fois.

**Comment by theflofly** [comment]
Hello, glad it helps.

`@Data` on a Car and Offer automatically add setters and getters.

Did you edit the pom.xml file, the versions for instance ?

**Comment by theflofly** [comment]
Are you sure that the MySQL db is running ? You can specify the dialect in the property file but normally it is not necessary.

**Comment by salemba** [comment]
Hello,
MySQL is running and the database was created before running the application.
I did not change anything in the pom.
I'm trying to debug the problem since. Can you please tell me if the car and the offer are ElasticSearch documents, where are you using MySQL?

**Comment by salemba** [comment]
Got It working finally!!
These are changes I've made to make it work for me: 
- Downgrade Mysql jdbc connector version from 5.1.36 to 5.1.20 (there is a minor bug in this driver which caused the error.
- I think you did not mention the version of ElasticSearch Server to use. This won't work with ES2.2 for instance. So, I had to downgrade to ES1.5.2 (just for safety, may be we can use newer versions).
- I replaced the _spring-boot-starter-data-jpa_ with _spring-boot-starter-jdbc.

Thanks again.

**Comment by theflofly** [comment]
The cars and offers are indeed Elasticsearch documents. The mysql database is used for the Spring batch metadata (i.e: job status, ...). The db is not mandatory, instead you can use an in memory H2 database.

**Comment by theflofly** [comment]
Glad to hear it.

Indeed sorry for the ES version.

> I replaced the spring-boot-starter-data-jpa with _spring-boot-starter-jdbc.

spring-boot-starter-data-elasticsearch is enough I think.

**Comment by FedrBodr** [comment]
i get some problem with configuration jpa multiple database - h2 and mysql - nullPointer,
I solve it with Downgrade Mysql jdbc connector version from 5.1.36 to 5.1.20 !

**Comment by axelosorio** [comment]
Springboot, Mysql & Digital Ocean

I have this problem with mysql in a droplet, I was working with spring boot.
I tried to change to spring-boot-starter-jdbc. but jdbc doesn't work for me because I already have some JPA spring annotations in my project, then return this to ...data-JPA
Even tried the downgrade mysql driver but, doesn't work too.

At the end, it works with this changes in the pom and in the application.properties.

By the way, I'm using the last version of mysql connector downloaded by maven 
At this time this is getting the mysql-connector-java-5.1.44.jar version.

The final dependencies in the pom about mysql were:
`<dependency>
		<groupId>mysql</groupId>
		<artifactId>mysql-connector-java</artifactId>
		<scope>runtime</scope>
</dependency>
<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>`


And my application.properties file under \src\main\resources is:

`spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://please_PUT_YOUR_PUBLIC_IP_not_LOCALHOST_not_127_0_0_1:3306/yourDatabaseName
spring.datasource.username=username_for_your_db
spring.datasource.password=password_for_your_db
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.http.multipart.max-file-size=14Mb
spring.http.multipart.max-request-size=14Mb`

the multipart and debug for sql only was for my config, the important part are the first 4 lines.
I hope this helps someone else, I lost 6 hours trying different configs until this work.

And don't forget to grant permissions in the mysql:
I tried all this , include the ' ' , I think that the last one is the good because it takes the IP from your server.

GRANT ALL ON your_dbname.* TO 'your_user_name@%';
GRANT ALL ON your_dbname.* TO 'your_user_name'@'%';
grant all privileges on your_dbname.* to 'your_user_name'@'127.0.0.1' identified by 'your_password';
grant all privileges on your_dbname.* to 'your_user_name'@'127.0.0.1' identified by 'your_password';
grant all privileges on your_dbname.* to 'your_user_name'@the_ip_from_the_mysql_server identified by 'your_password';
flush privileges;
